### ISSUE TITLE
Blocks of metals uncraftable now.

### ISSUE THREAD

**Issue by Iwerks** [TPPIDev/TestPackPleaseIgnore2#129] opened 2015-01-09 08:37 UTC
http://puu.sh/eh22B/c52b9b9966.jpg

Also copper switched to GT after processing and won't unify to TE so I don't waste space in my AE.

-_-;

**Comment by TwiiCe** [comment] 2015-01-11 11:49
A quick workaround (for the time being) is to melt them in a smeltry and dump the contents of the smeltry in a casting basin.
(The TiCo Crucible)

**Comment by esKaayY** [comment] 2015-01-13 08:58
Duplicate of https://github.com/TPPIDev/TestPackPleaseIgnore2/issues/120

**Closed by esKaayY** 2015-01-13 08:58 UTC

**Comment by TehNut** [comment] 2015-01-13 09:11
No, the blocks themselves are uncraftable. #120 is saying that uncrafting a block turns it to dusts.
