### ISSUE TITLE
Memory Leak on Server

### ISSUE THREAD

**Issue by Marcellas** [TPPIDev/TestPackPleaseIgnore2#331] opened 2015-09-09 02:57 UTC
I believe the culprit is BiomesO'Plenty... Didn't really see anything else that it point's to. It just tell player "timed out" when it disconnects/shuts down. 

Server Version TPPI2 0.2.1
Crash Log Paste: http://paste.ubuntu.com/12318307/

**Comment by TehNut** [comment] 2015-09-10 04:49
What happens if you allocate 4Gb instead of 2Gb?

**Comment by TehNut** [comment] 2015-09-12 02:19
Closing because this was probably caused by worldgen RAM usage on only 2Gb allocated.

**Closed by TehNut** 2015-09-12 02:19 UTC
