### ISSUE TITLE
TiCon Tools Despawn on Death

### ISSUE THREAD

**Issue by Sayshal** [TPPIDev/TestPackPleaseIgnore2#280] opened 2015-04-09 22:31 UTC
No errors in log, this is on TPPI2 Beta 0.1.1.

Reproducing:
1. Create TiCon tools legitimately via Smeltery (spawned in items seem to not vanish)
2. Make sure keepInv is off, as well as graves.
3. Die naturally (mob/fall damage)
4. All your shit is there except TiCon tools.

How I confirmed:
I tested this on my localhost server, with the only modifications being the addition of Treecapitator & ServerTools configured to backup. I have not tested this in single player, I'll edit this when I do, but it had a 100% reproduction rate between myself, and two friends.

**Comment by tterrag1098** [comment] 2015-04-09 22:33
That's extremely odd, because while playing once, I died in lava and returned to find my Tcon tools just fine.

**Comment by Sayshal** [comment] 2015-04-09 22:40
Just confirmed this also happens in ssp.

I'm going to try once more to do it in SMP, and if it works maybe one of you can hop on and see for yourself. We've enabled gravestones to counteract it for now.

**Comment by TehNut** [comment] 2015-04-09 23:33
Unable to reproduce in SSP.

http://tehnut.info/share/Vexm2A3Sx.mp4

**Comment by TehNut** [comment] 2015-04-28 20:03
@Sayshal Can you still reproduce this issue or should I close it?

**Comment by Sayshal** [comment] 2015-04-28 21:17
I cant reproduce it but its been reported to be happrning again so either
close it or lemme retest it in 0.1.5

**Closed** 2015-05-17 04:19 UTC
Labels: bug, Cannot Replicate
