### ISSUE TITLE
CTD Caused by Mining Dense Ore

### ISSUE THREAD

**Issue by Marcellas** [TPPIDev/TestPackPleaseIgnore2#325] opened 2015-08-15 00:19 UTC
When mining dense ores using a Fortune III, Auto-Smelt, Efficiency IV diamond pickaxe... I'm not sure if it is just that exact type or the combination of Fortune III and Auto-Smelt that causes the issue, but it happens regardless of the type of metal mined. It however does not effect coal or red stone dense ore that I have seen.

Here is the log: http://paste.ubuntu.com/12084524/

**Comment by TehNut** [comment] 2015-08-15 00:28
This is a ttCore/EnderCore issue that is unfixable. @tterrag1098

**Comment by TehNut** [comment] 2015-08-16 04:54
Oh, also a duplicate of #302

**Closed by TehNut** 2015-08-16 04:54 UTC
Labels: bug, Can't Fix, Confirmed, Crash, Cross Mod Bug/Exploit

**Comment by Ianaver** [comment] 2015-10-18 04:44
@Marcellas go to the EnderCore issue tracker and report it there, I suggest trying an updated version of enderio and endercore and testing that instead before reporting though (jenkins builds here http://ci.tterrag.com/job/EnderIO/ http://ci.tterrag.com/job/EnderCore/ ).

**Comment by TehNut** [comment] 2015-10-18 04:44
No, do not go there. It is only fixable on DenseOre's side.

**Comment by Ianaver** [comment] 2015-10-18 15:39
@TehNut it may be so but still maybe one of the authors know what caused it? I also need to test the new versions anyway since a lot has changed from when this issue was reported to now, ttcore is no more and is now endercore and autosmelt has received some improvements and bug fixes.

**Comment by Ianaver** [comment] 2015-10-18 16:13
@Marcellas @TehNut Well I tested the newest version of endercore and dense ores and there are no more issues

**Comment by TehNut** [comment] 2015-10-18 18:02
tterrag *is* the author.

**Comment by Ianaver** [comment] 2015-10-19 02:13
@TehNut I said authors but I meant for both mods! XD either way its fixed now in newest version of endercore :P
