### ISSUE TITLE
EnderIO ME Conduits connection issue.

### ISSUE THREAD

**Issue by calmcacil** [TPPIDev/TestPackPleaseIgnore2#133] opened 2015-01-10 21:29 UTC
Currently it seems like EIO's ME conduits dont care if you use a wrench to disable their connection, they seem like they currently are connected even if you disable the connection. They also seem not update in world when you break a connected device/cable. 

http://puu.sh/elkCR/cd386f00eb.jpg

**Comment by HaroldDaFrog** [comment] 2015-01-25 19:14
Yep, I've encountered this same thing. All we can do is blame Tterrag until EIO cleans it up a bit, not a huge problem.

**Comment by TehNut** [comment] 2015-01-31 10:22
Cannot reproduce.

![Nope][http://puu.sh/fgZ7H/d030e02e39.png]

**Comment by calmcacil** [comment] 2015-01-31 10:25
Try connecting it to something that isnt another EIO conduit and then break whatever it was connected to. I.e. Connect a ME Drive  and then break the drive.

**Comment by TehNut** [comment] 2015-01-31 10:48
Ah, I see. Yup

**Comment by tterrag1098** [comment] 2015-01-31 16:33
Is fixed in EIO dev builds

**Comment by TehNut** [comment] 2015-01-31 20:40
Coolio

**Closed** 2015-09-09 02:57 UTC
Labels: Confirmed, Fixed in Next Version, Update Required
