### ISSUE TITLE
[Suggestion] TSteelworks config

### ISSUE THREAD

**Issue by Cyrakrum** [TPPIDev/TestPackPleaseIgnore2#180] opened 2015-01-23 09:20 UTC
The high oven isn't smelting dense ores or osmium ore... Which I can't remember if the smeltery does dense ores but it definitely does osmium.

The high oven is currently set to output 2 ingots per ore... While I think the usual 3 is a bit too much, I think there should be a bit more incentive to build this beautiful behemoth. I propose that it be upped to 2.3 or 2.1 ingots, just a little boost considering how this isn't exactly hard to build.

Also I don't feel enough glass were given values in the steelworks config... So I wrote up a couple additonal ones (Most of the glass I could find in NEI, and most are generously set low with the exception of hardened glass and its enderIO counterpart)

		Botany:stained@*|10000
		Forestry:stained@*|17500
		Natura:NetherGlass@*|12500
		Railcraft:tile.railcraftglass@*|30000
		MineFactoryReloaded:stainedglass.block@*|12500
		ThermalExpansion:Glass@0|45000
		Ztones:tile.glaxx@*|17500
		chisel:glass@*|10000
		chisel:stained_glass_white@*|10000
		chisel:stained_glass_yellow@*|10000
		chisel:stained_glass_lightgray@*|10000
		chisel:stained_glass_brown@*|10000
		EnderIO:blockFusedQuartz@0|45000
		EnderIO:blockFusedQuartz@1|10000

Some of these values might need a boost for balance sake... But honestly I think the important part is the ability to make interesting tanks.

**Comment by Yulife** [comment] 2015-01-23 13:05
Calling @Ephys for dense ore support.

**Comment by Ephys** [comment] 2015-01-23 19:15
The version I'm working on will have ModTweaker support (working on this and an API right now) and copies the smelt list from TConstruct when the mod is loaded (that part is done but unreleased yet). I assume that will be sufficient to auto-add dense ore support

**Comment by Yulife** [comment] 2015-01-23 19:20
Modtweaker support? Whoa, that's nice.

**Comment by Ephys** [comment] 2015-01-24 00:21
I can confirm Dense Ores support will be in the next release http://i.imgur.com/4kzMgIn.png o/

**Comment by TehNut** [comment] 2015-01-24 00:28
\o/

Now, release it. ;)

**Comment by Cyrakrum** [comment] 2015-01-24 02:03
Alright just an update on the added glasses as well as a bug relating to them... Soo the * wildcard only works with the block that has 0 for the meta data, even on the default minecraft stained glass... And I typoed the railcraft glass. So here is my tested (and commented) updated glasses (with new glasses) The size balances probably need to be worked out... I set hardened glass and fuse quartz waay up because I mean they obviously take more effort than the other ones, so I also threw warded glass in there with them because research cost etc... Andddd I just saw Ephys added the botania glasses... I feel like the point you're at where you're making alfglass you need terrasteel and a large mana pool... I feel like 17500 capacity isn't doing that justice... Anyways here's my updated config change thingy (And tested!)

		# These only work with the block @0 meta data (It's the same with the default glasses as well)
		Forestry:stained@*|17500
		Railcraft:tile.railcraft.glass@*|30000
		MineFactoryReloaded:stainedglass.block@*|12500
		Ztones:tile.glaxx@*|17500
		chisel:glass@*|10000
		chisel:stained_glass_white@*|10000
		chisel:stained_glass_yellow@*|10000
		chisel:stained_glass_lightgray@*|10000
		chisel:stained_glass_brown@*|10000
		
		# These just plain don't work... I'm not quite sure why... 
		EnderIO:blockFusedQuartz@0|45000
		EnderIO:blockFusedQuartz@1|10000
		Botany:stained|10000
		Thaumcraft:blockCosmeticOpaque|45000
		
		# Should all work now it's just a question of balancing values
		appliedenergistics2:tile.BlockQuartzGlass|30000
		Botania:elfGlass|17500
		Botania:manaGlass|12500
		ThermalExpansion:Glass@0|45000
		Natura:NetherGlass@1|12500

**Comment by Ephys** [comment] 2015-01-24 03:10
> These just plain don't work... I'm not quite sure why... 
Double check the log to see why they're not registered, it's probably because they have tile entities
I'll probably steal the fluid values again once everybody is settled with them as I'm seriously bad at balancing that

Yeah I also noticed the * didn't work well (which is quite recent, must have broke something), I'll fix that before the official release *mental note*

**Comment by TehNut** [comment] 2015-01-24 03:37
@Ephys Since we have your attention here, would you like access to a Jenkins build server instead of releasing on Github?

**Comment by Ephys** [comment] 2015-01-24 12:53
That would be a great thing to have ! But I'd most likely use it for dev/test builds and still use github to post stable builds

**Comment by TehNut** [comment] 2015-01-24 13:19
Bother me on IRC (same name) tomorrow and I'll set you up.

**Comment by Ephys** [comment] 2015-01-24 13:22
Alright ! *adds /another/ mental note*

**Closed** 2015-01-25 05:19 UTC

**Comment by Yulife** [comment] 2015-01-25 15:34
@Ephys is your Minetweaker integration ready for documentation? ;)

**Comment by Ephys** [comment] 2015-01-25 16:21
Should be, if you want to test you can get the build here http://tehnut.info/jenkins/job/TSteelworks/2/

There is a doc stub here too, if you wish to expand it (caus I just lazily copypasted the method names):
https://github.com/Ephys/TinkersSteelworks/tree/api#minetweaker-support

**Comment by Yulife** [comment] 2015-01-25 16:36
Will take a look at it :)
