### ISSUE TITLE
Mekanism Circuits Auto Unification

### ISSUE THREAD

**Issue by Iwerks** [TPPIDev/TestPackPleaseIgnore2#118] opened 2015-01-06 19:44 UTC
Mekanism Circuits auto unify to IC2 circuits when thrown on the ground similar to the essence berries to ore berries.

**Comment by TehNut** [comment] 2015-01-08 22:24
I SAID MIGHT, NOT WILL. STUPID COMMIT CLOSING THINGS.

**Comment by UndeadZeratul** [comment] 2015-01-08 23:18
Don't you just love being able to close issues automatically with commit comments?  Aren't they just the best?

**Comment by esKaayY** [comment] 2015-01-13 08:52
Duplicate of https://github.com/TPPIDev/TestPackPleaseIgnore2/issues/92

**Closed by esKaayY** 2015-01-13 08:52 UTC
