### ISSUE TITLE
NEI Search Kicks from game/server

### ISSUE THREAD

**Issue by sahaka** [TPPIDev/TestPackPleaseIgnore2#327] opened 2015-08-24 01:25 UTC
If you search or start to search for certain words NEI will crash and you will be kicked from the game. Opening your inventory in the future causes the crash as well. You can only delete the NEI client data to get back in and it is easily repeatable. I had an empty inventory and was searching NEI for "strongbox" but only got up to "str" before it kicked me. This is the console output:

[21:17:43 WARN]: ****************************************
[21:17:43 WARN]: * Null fluid supplied to fluidstack. Did you try and create a stack for an unregistered fluid?
[21:17:43 WARN]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:35)
[21:17:43 WARN]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67)
[21:17:43 WARN]: *  at codechicken.core.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:18)
[21:17:43 WARN]: *  at codechicken.core.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:28)
[21:17:43 WARN]: *  at codechicken.enderstorage.storage.liquid.EnderLiquidStorage$Tank.<init>(EnderLiquidStorage.java:20)
[21:17:43 WARN]: *  at codechicken.enderstorage.storage.liquid.EnderLiquidStorage.<init>(EnderLiquidStorage.java:35)...
[21:17:43 WARN]: ****************************************
[21:17:43 ERROR]: There was a critical exception handling a packet on channel ES
java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36) ~[FluidStack.class:1.7.10-1481.148]
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:67) ~[FluidStack.class:1.7.10-1481.148]
	at codechicken.core.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:18) ~[ExtendedFluidTank.class:?]
	at codechicken.core.fluid.ExtendedFluidTank.<init>(ExtendedFluidTank.java:28) ~[ExtendedFluidTank.class:?]
	at codechicken.enderstorage.storage.liquid.EnderLiquidStorage$Tank.<init>(EnderLiquidStorage.java:20) ~[EnderLiquidStorage$Tank.class:?]
	at codechicken.enderstorage.storage.liquid.EnderLiquidStorage.<init>(EnderLiquidStorage.java:35) ~[EnderLiquidStorage.class:?]
	at codechicken.enderstorage.storage.EnderLiquidStoragePlugin.createEnderStorage(EnderLiquidStoragePlugin.java:17) ~[EnderLiquidStoragePlugin.class:?]
	at codechicken.enderstorage.api.EnderStorageManager.getStorage(EnderStorageManager.java:161) ~[EnderStorageManager.class:?]
	at codechicken.enderstorage.storage.liquid.TankSynchroniser$PlayerItemTankCache.track(TankSynchroniser.java:170) ~[TankSynchroniser$PlayerItemTankCache.class:?]
	at codechicken.enderstorage.storage.liquid.TankSynchroniser$PlayerItemTankCache.handleVisiblityPacket(TankSynchroniser.java:232) ~[TankSynchroniser$PlayerItemTankCache.class:?]
	at codechicken.enderstorage.storage.liquid.TankSynchroniser.handleVisiblityPacket(TankSynchroniser.java:269) ~[TankSynchroniser.class:?]
	at codechicken.enderstorage.internal.EnderStorageSPH.handlePacket(EnderStorageSPH.java:20) ~[EnderStorageSPH.class:?]
	at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:115) ~[PacketCustom$ServerInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:75) ~[PacketCustom$CustomInboundHandler.class:?]
	at codechicken.lib.packet.PacketCustom$CustomInboundHandler.channelRead0(PacketCustom.java:62) ~[PacketCustom$CustomInboundHandler.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:1.7.10-1481.148]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
[21:17:43 INFO]: sahaka lost connection: A fatal error has occured, this connection is terminated

**Comment by TehNut** [comment] 2015-08-24 03:17
Pack version?

**Comment by sahaka** [comment] 2015-08-24 03:20
0.1.1

**Comment by TehNut** [comment] 2015-08-24 03:25
This isn't reproducable in `0.1.5`, so I'll assume it was fixed in one of the mod updates. Will leave this open until `0.1.1` is not the recommended build.

**Comment by sahaka** [comment] 2015-08-24 14:09
Ok. Can't wait till the next version becomes the recommended-stable :) 

But just to keep comprehensive documentation of the issue incase it comes up again I have some more information:

* It is consistently that same issue with fluid stacks. 
* we have discovered that the reproducibility is only for the particular person and only for about an hour. So if person A gets kicked with the word strong they can reliably reproduce that for the next hour or so but person B cannot. Instead person B gets kicked with a different word. So it definitely has some sort of random element to it. 
* it also seems to happen after you have had the client running for a bit or have been connected to the server for a while. Almost as if it needs time to snowball into instability like a memory leak.

**Comment by TehNut** [comment] 2015-08-27 22:15
Caused by a modification to the pack.

**Closed by TehNut** 2015-08-27 22:15 UTC
Labels: Fixed in Next Version
