### ISSUE TITLE
Blocks still turn in to dust

### ISSUE THREAD

**Issue by HaroldDaFrog** [TPPIDev/TestPackPleaseIgnore2#197] opened 2015-02-14 16:49 UTC
Iron block goes to diamond dust, same with diamond, etc. Been out of the loop for like 3 weeks, no clue if this is supposed to have been fixed, but it is a thing.

**Comment by Slysam** [comment] 2015-02-14 17:44
From what I saw last night, Iron blocks turn into iron dust and Osmium blocks turn into Osmium dust, but Copper Blocks turn into Copper bars.

**Comment by TehNut** [comment] 2015-02-14 17:47
Duplicate of #120

**Closed by TehNut** 2015-02-14 17:47 UTC
