### ISSUE TITLE
Hardcore Ender Expansion TNT dupes

### ISSUE THREAD

**Issue by Oaurn** [TPPIDev/TestPackPleaseIgnore2#275] opened 2015-04-08 17:44 UTC
Hey all, was playing on a TPPI2 server and noticed that the Enhanced TNT from the Hardcore Ender Expansion mod seems to be duping itself when given a redstone signal.  

Only thing that has been added to the modpack was updating botania to the most recent version.  Here is a video showing the issue:

>snip - TehNut

Basically the TNT is being used to create mana through botania's Entropinium's.  I was using regular TNT but it exploded a few times damaging the area, so I decided to give the feather enhanced(no block damage) TNT a try.  It is definitely giving a real block back and not a ghost block.  

Not sure if it works with all enhanced TNT, but ill give it a try.  Not that pressing an issue in the grand scheme of things, but a dupe is a dupe.

Thanks guys

**Comment by chylex** [comment] 2015-04-08 19:56
Which version of HEE does TPPI2 have? You can see it using /heeadmin version.

**Comment by TehNut** [comment] 2015-04-08 20:41
@chylex We currently have 1.7.1. In a few days, we'll be updating the pack to latest of all mods. Will report back to you afterwards.

**Comment by chylex** [comment] 2015-05-09 11:01
Right. Bug confirmed, but it's not a dupe, the TNT does not actually explode, it just drops itself and client thinks it was set off. Use flint and steel until the bug is fixed.

**Comment by chylex** [comment] 2015-05-31 00:04
Fixed in HEE 1.8.1.

**Closed** 2015-09-09 02:57 UTC
Labels: Fixed in Next Version, Update Required
